name: SMPCore
main: com.SMPCore.Main
version: 1.0
api-version: 1.20

depend:
  - MenuAPI
  - WorldGuard
  - WorldEdit
  - ParticleNativeAPI
  - NBTAPI
  - SoundParticleAPI
  - Essentials
  - CustomCrafting


commands:
  protectarea:
    aliases:
      - pa
      - areaprotect
      - ap
  waypoint:
    usage: /waypoint
  waypoints:
    usage: /waypoints
  skills:
    usage: /skills
  warps:
    usage: /warps
  ability:
    usage: /ability
    aliases:
      - abilities